[package]
name = "blue_boy_adventure_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fast_log = "1.6.12"
ggez = "0.9.3"
log = "0.4.20"
mint = "0.5.9"
toml = "0.8.8"
